<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'env',
  'APP_SECRET' => 'd3ee2d1025a2b46f01d47fda6e436e15',
  'MAILER_DSN' => 'null://localhost',
  'DATABASE_URL' => 'mysql://symfony:dfx59zUPlmao!@127.0.0.1:3306/symfony',
  'MAILER_URL' => 'null://localhost',
);
