#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /en
        permanent: true